variables:
  # proyecto en ocp
  NAME_SPACE_OCP: "norma-tecnica"
  STEREOTYPE: "FRONT"
  PROJECT_NAME: "norma-tecnica"
include:
  # ruta relativa del repositorio de plantillas en gitlab
  - project: '00-arquitectura/gitlab-ci-pipeline'
    # rama del proyecto
    ref: master
    # ruta relativa de la plantilla de pipeline dentro del repositorio de plantillas, este cambia según el framework a utilizar si es springboot deberá ser springboot.yml
    file:
      - 'templates/angular-prodocp-prodrosa-devrosa-qaocp.yml'
